-- MySQL Script generated by MySQL Workbench
-- Sat Feb  3 11:18:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pib
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pib
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pib` DEFAULT CHARACTER SET utf8 ;
USE `pib` ;

-- -----------------------------------------------------
-- Table `pib`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pib`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `populacao` DOUBLE NOT NULL,
  `pais` VARCHAR(100) NOT NULL,
  `ano` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pib`.`pib`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pib`.`pib` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idPais` INT NOT NULL,
  `consumo` DOUBLE NOT NULL,
  `investimento` DOUBLE NOT NULL,
  `gastosGoverno` DOUBLE NOT NULL,
  `exportacoes` DOUBLE NOT NULL,
  `importacoes` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_pib_pais_idx` (`idPais` ASC),
  CONSTRAINT `fk_pib_pais`
    FOREIGN KEY (`idPais`)
    REFERENCES `pib`.`pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `pib` ;

-- -----------------------------------------------------
-- Placeholder table for view `pib`.`calculo_pib`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pib`.`calculo_pib` (`totalPib` INT, `pais` INT);

-- -----------------------------------------------------
-- Placeholder table for view `pib`.`calculo_pib_per_capita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pib`.`calculo_pib_per_capita` (`totalPib` INT, `pais` INT);

-- -----------------------------------------------------
-- View `pib`.`calculo_pib`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pib`.`calculo_pib`;
USE `pib`;
CREATE  OR REPLACE VIEW `calculo_pib` AS SELECT (
	p.consumo + p.investimento + gastosGoverno + (exportacoes - importacoes)
) AS totalPib, pa.pais FROM pib AS p
INNER JOIN pais AS pa ON p.idPais = pa.id;

-- -----------------------------------------------------
-- View `pib`.`calculo_pib_per_capita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pib`.`calculo_pib_per_capita`;
USE `pib`;
CREATE  OR REPLACE VIEW `calculo_pib_per_capita` AS SELECT ((
	p.consumo + p.investimento + gastosGoverno + (exportacoes - importacoes)
) / pa.populacao) AS totalPib, pa.pais FROM pib AS p
INNER JOIN pais AS pa ON p.idPibPais = pa.id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
